version: 2

builds:
  # Linux AMD64 构建 (本地编译器)
  - id: linux-amd64
    env:
      - CGO_ENABLED=1
    main: ./cmd/server
    binary: nodepassdash
    goos:
      - linux
    goarch:
      - amd64
    flags:
      - -trimpath
    ldflags:
      - -s -w -X main.Version={{ .Tag }}
    tags:
      - sqlite_omit_load_extension
      
  # Linux ARM64 构建 (交叉编译器)
  - id: linux-arm64
    env:
      - CGO_ENABLED=1
      - CC=aarch64-linux-gnu-gcc
      - CXX=aarch64-linux-gnu-g++
    main: ./cmd/server
    binary: nodepassdash
    goos:
      - linux
    goarch:
      - arm64
    flags:
      - -trimpath
    ldflags:
      - -s -w -X main.Version={{ .Tag }}
    tags:
      - sqlite_omit_load_extension
      
  # Windows 构建 (交叉编译器)
  - id: windows
    env:
      - CGO_ENABLED=1
      - CC=x86_64-w64-mingw32-gcc
      - CXX=x86_64-w64-mingw32-g++
    main: ./cmd/server
    binary: nodepassdash
    goos:
      - windows
    goarch:
      - amd64
    flags:
      - -trimpath
    ldflags:
      - -s -w -X main.Version={{ .Tag }}
    tags:
      - sqlite_omit_load_extension
      
  # macOS 构建需要特殊设置，暂时跳过
  # 如果需要 macOS 支持，建议使用单独的 macOS runner

archives:
  - format: tar.gz
    format_overrides:
      - goos: windows
        format: zip

release:
  # 自动检测预发布版本 (包含 alpha, beta, rc 等)
  prerelease: auto
  # 发布名称模板
  name_template: "NodePass Dashboard {{ .Tag }}"
  # 允许替换已存在的发布
  replace_existing_draft: true
  # 发布说明
  header: |
    ## NodePass Dashboard {{ .Tag }}
    
    ### 🎉 新版本发布
    
    感谢使用 NodePass Dashboard！
    
  footer: |
    
    ### 📥 下载说明
    - **Linux**: 下载 `nodepassdash_Linux_*.tar.gz`
    - **Windows**: 下载 `nodepassdash_Windows_*.zip`
    - **macOS**: 暂不支持，请使用 Docker 版本
    
    ### 🐳 Docker 镜像
    ```bash
    docker pull ghcr.io/nodepass/nodepass-webui:{{ .Tag }}
    ``` 