services:
  # NodePass 应用 - 使用GitHub发布的镜像
  nodepassdash:
    image: ghcr.io/nodepassproject/nodepassdash:latest
    container_name: nodepassdash
    environment:
      # 应用配置(修改这里)
      - JWT_SECRET=your-super-secret-jwt-key-change-this-in-production
    ports:
      - "3000:3000"  # 整合的Next.js应用
    volumes:
      # 挂载配置和日志
      - ./config:/app/config:ro
      # SQLite 数据库文件
      - ./public:/app/public
      # 日志和数据目录,如需挂载，请先赋予文件夹权限```chmod 777 logs```，否则可能会导致容器启动失败
      # - ./logs:/app/logs
      # - ./data:/app/data
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:3000/api/health"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 60s
