services:
  # NodePass 应用
  nodepassdash:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: nodepassdash
    ports:
      - "4000:3000"
    volumes:
      # 挂载配置和日志
      - ./config:/app/config:ro
      # SQLite 数据库文件
      - ./public:/app/public
    restart: unless-stopped
    # 健康检查
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:3000/api/health"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 60s
