name: Docker CI (beta)

on:
  push:
    branches:
      - "*-beta"
    tags:
      - "v*.*.*.beta*"
      - "v*.*.*-beta*"
jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract version
        id: vars
        run: |
          if [[ "${GITHUB_REF}" == refs/tags/* ]]; then
            VERSION=${GITHUB_REF#refs/tags/}
          else
            VERSION=${GITHUB_SHA::7}-beta
          fi
          echo "version=$VERSION" >> $GITHUB_OUTPUT

      - name: Prepare metadata
        id: meta
        run: |
          REPO_LC=$(echo "${GITHUB_REPOSITORY}" | tr '[:upper:]' '[:lower:]')
          echo "repo=$REPO_LC" >> $GITHUB_OUTPUT
          echo "version=${{ steps.vars.outputs.version }}" >> $GITHUB_OUTPUT

      - name: Build and push Docker image (beta)
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: |
            ghcr.io/${{ steps.meta.outputs.repo }}:${{ steps.vars.outputs.version }}
            ghcr.io/${{ steps.meta.outputs.repo }}:beta
          build-args: |
            VERSION=${{ steps.vars.outputs.version }}
          platforms: linux/amd64

      - name: Output version info
        run: |
          echo "🏷 Version: ${{ steps.vars.outputs.version }}"
          echo "📦 Image Tags:"
          echo "  ghcr.io/${{ steps.meta.outputs.repo }}:${{ steps.vars.outputs.version }}"
          echo "  ghcr.io/${{ steps.meta.outputs.repo }}:beta" 